name: Test binary

# only one per github sha can be run
concurrency:
  group: cd-release-nightly

on: push

jobs:
  npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: |
          VERSION=next
          echo VERSION $VERSION
          echo "::set-output name=version::$VERSION"
    outputs:
      version: ${{ steps.version.outputs.version }}

  binary:
    name: Create lodestar binaries
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        include:
          - os: windows
            build: npx caxa --input . --output "lodestar-windows-${{ needs.npm.outputs.version }}.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/node_modules/.bin/lodestar"
            artifact: lodestar-windows-${{ needs.npm.outputs.version }}.exe
          - os: macos
            build: |
              npx caxa --input . --output "lodestar.app" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/node_modules/.bin/lodestar"
              tar -czf "lodestar-macos-${{ needs.npm.outputs.version }}.app.tgz" "lodestar.app"
            artifact: lodestar-macos-${{ needs.npm.outputs.version }}.app.tgz
          - os: ubuntu
            build: |
              npx caxa --input . --output "lodestar" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/node_modules/.bin/lodestar"
              tar -czf "lodestar-linux-${{ needs.npm.outputs.version }}.tgz" "lodestar"
            artifact: lodestar-linux-${{ needs.npm.outputs.version }}.tgz
    runs-on: ${{matrix.os}}-latest
    needs: npm
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
          registry-url: "https://registry.npmjs.org"
      - run: |
          yarn global add caxa
          yarn add @chainsafe/lodestar-cli@${{ needs.npm.outputs.version }}
          ${{ matrix.build }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}